# Generated by Django 4.2.11 on 2024-05-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_key_activationkey_activation_keys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activationkey",
            old_name="activation_keys",
            new_name="activation_key",
        ),
    ]
